Repository ESTiOSAI/iCo, pull requests merged in 2025-08, with the labels that each got.

#50 AI 리포트 UI 구현
  AIProject/AIProject/Features/Base/SegmentedControlView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
Labels: Feature

#74 extractJSON 함수 String extension으로 이동
  AIProject/AIProject/Core/Util/String+ExtractJSON.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
Labels: Refactor

#85 ReportView 리팩토링: 프롬프트 간소화, fetch method 위치 이동
  AIProject/AIProject/Core/Remote/APIService/AlanAPIService.swift
  AIProject/AIProject/Data/Response/AlanResponse/Content/CoinOverviewDTO.swift
  AIProject/AIProject/Data/Response/AlanResponse/Content/CoinTodayNewsDTO.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
Labels: Fix

#89 코인 추천 뷰모델에서 에러 처리 하도록 변경 & JSON 마크다운 제거 적용
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/DashboardViewModel.swift
Labels: Refactor

#90 코인 상세 정보 - AI 리포트 코인 개요 캐시 적용
  AIProject/AIProject/Core/Remote/APIService/AlanAPIService.swift
  AIProject/AIProject/Data/Response/AlanResponse/Content/CoinTodayNewsDTO.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
Labels: Feature

#98 SubHeaderView에서 Description을 받을 수 있도록 수정
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/Base/SubheaderView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
Labels: Design

#102 대시보드 - UI 구현
  AIProject/AIProject/Data/Model/FearGreed.swift
  AIProject/AIProject/Data/Model/Sentiment.swift
  AIProject/AIProject/Features/Dashboard/View/DashboardSectionView.swift
  AIProject/AIProject/Features/Dashboard/View/DashboardView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
  AIProject/AIProject/Features/Dashboard/View/TodayCoinInsightView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/TodayCoinInsightViewModel.swift
Labels: Feature

#103 대시보드 - AI 브리핑 공포탐욕지수
  AIProject/AIProject/Core/Remote/APIService/FearGreedAPIService.swift
  AIProject/AIProject/Data/Response/FearGreedResponse/FearGreedResponseDTO.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
Labels: Feature

#104 검색 구현 및 swift-async-algorithms 라이브러리 추가
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AIProject/AIProject/Core/Remote/APIService/UpbitAPIService.swift
  AIProject/AIProject/Core/Util/Data+Util.swift
  AIProject/AIProject/Data/Model/Coin.swift
  AIProject/AIProject/Features/Search/EmptySearchResultView.swift
  AIProject/AIProject/Features/Search/RecentSearchListView.swift
  AIProject/AIProject/Features/Search/RecentSearchView.swift
  AIProject/AIProject/Features/Search/SearchResultListView.swift
  AIProject/AIProject/Features/Search/SearchResultView.swift
  AIProject/AIProject/Features/Search/SearchView.swift
  AIProject/AIProject/Features/Search/ViewModel/SearchViewModel.swift
Labels: Feature, Build

#125 북마크 CoreData Entity 수정 및 공통 컴포넌트 추가
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject/Core/Local/AIProject.xcdatamodeld/AIProject.xcdatamodel/contents
  AIProject/AIProject/Core/Local/Persistence.swift
  AIProject/AIProject/Core/Remote/APIService/AlanAPIService.swift
  AIProject/AIProject/Data/CoreData/Bookmark/BookmarkEntity+Convenience.swift
  AIProject/AIProject/Data/CoreData/Bookmark/BookmarkEntity+CoreDataProperties.swift
  AIProject/AIProject/Data/CoreData/Bookmark/BookmarkManager.swift
  AIProject/AIProject/Data/Model/AlanAction.swift
  AIProject/AIProject/Data/Response/AlanResponse/Content/PortfolioBriefingDTO.swift
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/RoundedButton.swift
  AIProject/AIProject/Features/Base/SortToggleButton.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/CoinRowView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/BookmarkViewModel.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageProcessViewModel.swift
  AIProject/AIProject/Info.plist
Labels: Feature, Fix

#130 이미지 분석 작업 취소 기능 구현하기
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientAccentLight.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientAccentProminent.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientDefaultLight.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientDefaultProminent.colorset/Contents.json
  AIProject/AIProject/Core/Util/Gradient+Util.swift
  AIProject/AIProject/Core/Util/ShapeStyle+Util.swift
  AIProject/AIProject/Data/Model/ImageProcessError.swift
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/RoundedButton.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkBulkInsert/BookmarkBulkInsertView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageProcessViewModel.swift
Labels: Feature, Design

#147 Google service 제거 및 cache 제거
  AIProject/AIProject/App/Resource/GoogleService-Info.plist
Labels: Fix

#148 RoundedRectangleFillButton 개선하기
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/RoundedRectangleFillButton.swift
Labels: Design

#151 마이페이지 화면 - 테마 변경 기능 구현
  AIProject/AIProject/App/Source/AIProjectApp.swift
  AIProject/AIProject/Data/Model/Theme.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeManager.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeRow.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
  AIProject/AIProject/Features/MyPage/View/ThemeView.swift
Labels: Feature

#127 네트워크 에러 처리 세분화
  AIProject/AIProject/Core/Network/NetworkError.swift
  AIProject/AIProject/Core/Remote/APIService/AlanAPIService.swift
  AIProject/AIProject/Core/Remote/Client/NetworkClient.swift
  AIProject/AIProject/Data/Model/Prompt.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/TodayCoinInsightViewModel.swift
Labels: Feature

#153 온보딩 - 투자 성향 선택 구현
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject.xcodeproj/xcshareddata/xcschemes/AIProject.xcscheme
  AIProject/AIProject/Data/Model/AppStorageKey.swift
  AIProject/AIProject/Data/Model/RiskTolerance.swift
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
Labels: Feature

#157 북마크 기능 Entity 변경 반영 - ChartViewModel 호출부 수정
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Refactor

#192 DefaultProgressView, 코인별 AI 리포트 디자인 적용
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoBackgroundBlue.colorset/Contents.json
  AIProject/AIProject/Data/Model/CoinArticle.swift
  AIProject/AIProject/Data/Model/Prompt.swift
  AIProject/AIProject/Data/Model/ResponseStatus.swift
  AIProject/AIProject/Data/Response/AlanResponse/Content/CoinArticleDTO.swift
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/Base/StatusSwitch.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportNewsSectionView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkBulkInsert/ContentSection.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
Labels: Feature, Design

#191 검색 화면 디자인 적용 및 개선
  AIProject/AIProject/Data/Model/Coin.swift
  AIProject/AIProject/Features/Base/CircleDeleteButton.swift
  AIProject/AIProject/Features/ChatBot/View/BotMessageView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
  AIProject/AIProject/Features/ChatBot/View/UserMessageView.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Search/EmptySearchResultView.swift
  AIProject/AIProject/Features/Search/RecentSearchListView.swift
  AIProject/AIProject/Features/Search/RecentSearchView.swift
  AIProject/AIProject/Features/Search/SearchBarView.swift
  AIProject/AIProject/Features/Search/SearchListView.swift
  AIProject/AIProject/Features/Search/SearchResultListView.swift
  AIProject/AIProject/Features/Search/SearchResultView.swift
  AIProject/AIProject/Features/Search/SearchView.swift
  AIProject/AIProject/Features/Search/ViewModel/SearchViewModel.swift
Labels: Design, Refactor

#197 SubheaderView 디자인 적용
  AIProject/AIProject/Features/Base/SubheaderView.swift
Labels: Design

#201 북마크 뷰 디자인 적용
  AIProject/AIProject/Core/Remote/APIService/CoinGeckoAPIService.swift
  AIProject/AIProject/Core/Util/String+Util.swift
  AIProject/AIProject/Data/Model/Prompt.swift
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/Base/RoundedRectangleFillButton.swift
  AIProject/AIProject/Features/Base/SortToggleButton.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/CoinRowView.swift
Labels: Design

#200 코인 추천 디자인 적용 with 더미데이터
  AIProject/AIProject/App/Resource/Assets.xcassets/AIBackgroundGradientLight.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AIBackgroundGradientProminent.colorset/Contents.json
  AIProject/AIProject/Data/Model/Prompt.swift
  AIProject/AIProject/Data/Model/RecommendCoin.swift
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCardView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/RecommendCoinViewModel.swift
Labels: Design

#198 코인 리스트 UI
  AIProject/AIProject.xcodeproj/xcshareddata/xcschemes/AIProject.xcscheme
  AIProject/AIProject/Core/Remote/APIService/UpbitTickerService.swift
  AIProject/AIProject/Core/Remote/Client/WebSocket+Model.swift
  AIProject/AIProject/Core/Remote/Client/WebSocketClient.swift
  AIProject/AIProject/Core/Remote/Client/WebSocketClient2.swift
  AIProject/AIProject/Data/Model/CoinListModel.swift
  AIProject/AIProject/Features/Base/SortToggleButton.swift
  AIProject/AIProject/Features/Market/CoinList/CoinCell.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListViewModel.swift
  AIProject/AIProject/Features/Market/CoinList/CoinSortButton.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/MarketViewModel.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
Labels: Feature, Design, Refactor

#203 마이페이지 홈 디자인 적용하기
  AIProject/AIProject/Features/MyPage/MyPageView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageMenuRow.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
Labels: Design

#205 마이페이지 테마 변경 화면 - 여백 변경
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Design, Refactor

#212 멘토링 피드백 반영
  AIProject/AIProject/Data/Model/Prompt.swift
  AIProject/AIProject/Data/Model/Sentiment.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/TodayCoinInsightViewModel.swift
Labels: Design

#225 Fix/coinlist error kh
  AIProject/AIProject/Core/Remote/APIService/CoinGeckoAPIService.swift
  AIProject/AIProject/Core/Remote/APIService/UpbitAPIService.swift
  AIProject/AIProject/Core/Remote/Client/WebSocketClient2.swift
  AIProject/AIProject/Data/Model/AppStorageKey.swift
  AIProject/AIProject/Data/Model/CoinListModel.swift
  AIProject/AIProject/Features/Base/CachedAsyncImage.swift
  AIProject/AIProject/Features/Main/MainTabView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinCell.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListStore.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinSortButton.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/MarketViewModel.swift
  AIProject/AIProject/Features/MyPage/View/CoinRowView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageLoader.swift
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
  AIProject/AIProject/Features/Onboarding/OnboardingViewModel.swift
Labels: Feature, Fix

#230 다크모드 색상 에셋 변경하기
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoAccent.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoBackground.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoBackgroundAccent.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoBackgroundWhite.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientAccentLight.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientAccentProminent.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientDefaultLight.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoGradientDefaultProminent.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoLabel.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AICoLabelSecondary.colorset/Contents.json
  AIProject/AIProject/App/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
Labels: Design

#260 ChartViewModel - 가격 불러오기 실패 로그/메모리 릭 수정
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Fix

#262 테스트 + ticker 애니메이션 및 구조 개선 + image 버그 픽스
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject.xcodeproj/xcshareddata/xcschemes/AIProjectTests.xcscheme
  AIProject/AIProject/Core/Remote/APIService/CoinGeckoAPIService.swift
  AIProject/AIProject/Core/Remote/APIService/UpbitAPIService.swift
  AIProject/AIProject/Core/Remote/APIService/UpbitTickerService.swift
  AIProject/AIProject/Core/Remote/Client/BaseWebSocketClient.swift
  AIProject/AIProject/Core/Remote/Client/Reconnectable+Model.swift
  AIProject/AIProject/Core/Remote/Client/ReconnectableSocket.swift
  AIProject/AIProject/Core/Remote/Client/SocketEngine.swift
  AIProject/AIProject/Core/Remote/Client/WebSocket+Model.swift
  AIProject/AIProject/Core/Remote/Client/WebSocketClient.swift
  AIProject/AIProject/Core/Remote/Client/WebSocketClient2.swift
  AIProject/AIProject/Data/Model/CoinListModel.swift
  AIProject/AIProject/Data/Request/UpbitRequest.swift
  AIProject/AIProject/Data/Response/UpbitResponse/CoinDTO.swift
  AIProject/AIProject/Data/Response/UpbitResponse/RealTimeTickerDTO.swift
  AIProject/AIProject/Data/Response/UpbitResponse/TickerDTO.swift
  AIProject/AIProject/Features/Main/MainTabView.swift
  AIProject/AIProject/Features/Market/CoinList/BlinkBorderOnChange.swift
  AIProject/AIProject/Features/Market/CoinList/CoinCell.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListHeaderView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListStore.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/CoinList/TickerViewModel.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/MarketViewModel.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageLoader.swift
  AIProject/AIProject/Features/Onboarding/OnboardingViewModel.swift
  AIProject/AIProjectTests/ReconnectableWebSocketTests.swift
  AIProject/AIProjectTests/UpbitTicketEncodeTests.swift
  AIProject/AIProjectTests/WebSocketTests.swift
Labels: Feature, Design, Refactor, Fix

#266 대시보드 코인 추천 카드 애니메이션 관련 추가 작업 및 자잘한 UI 변경
  AIProject/AIProject/Features/Dashboard/View/RecommendCardView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinScreen.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendHeaderView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/RecommendCoinViewModel.swift
Labels: Feature, Design

#270 등락폭 필터 추가/아이콘 변경, 소켓 스트리밍 버그 수정
  AIProject/AIProject/Core/Remote/APIService/UpbitTickerService.swift
  AIProject/AIProject/Core/Remote/Client/BaseWebSocketClient.swift
  AIProject/AIProject/Core/Remote/Client/ReconnectableSocket.swift
  AIProject/AIProject/Features/Base/SortToggleButton.swift
  AIProject/AIProject/Features/Market/CoinList/CoinCell.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListHeaderView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/CoinList/HeaderToggleButton.swift
  AIProject/AIProject/Features/Market/CoinList/TickerViewModel.swift
  AIProject/AIProject/Features/Market/MarketStore.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageLoader.swift
  AIProject/AIProject/Features/Onboarding/OnboardingViewModel.swift
Labels: Feature, Fix

#287 북마크 코인 브리핑 캐시 키 겹침 오류
  AIProject/AIProject/Core/Util/String+Util.swift
  AIProject/AIProject/Data/API/Alan/AlanAPIService.swift
  AIProject/AIProject/Domain/Model/Common/Prompt.swift
Labels: Fix

#300 코인별 AI 리포트 아이패드 대응
  AIProject/AIProject/Core/Util/String+Util.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportNewsSectionView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/Dashboard/View/AIBriefingView.swift
Labels: Design

#284 챗봇 개선사항 적용 & 아이패드 대응
  AIProject/AIProject/Features/ChatBot/View/BotMessageView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatInputView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatScrollView.swift
  AIProject/AIProject/Features/ChatBot/View/UserMessageView.swift
  AIProject/AIProject/Features/ChatBot/ViewModel/ChatBotViewModel.swift
Labels: Feature, Fix

#308 앨런 추천 코인 정확도 이슈 개선 + 디자인 수정
  AIProject/AIProject/Domain/Model/Common/Prompt.swift
  AIProject/AIProject/Features/Dashboard/View/RecomendationPlaceholderCardView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinScreen.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/RecommendCoinViewModel.swift
Labels: Design, Fix

#309 마켓 화면 스플릿뷰 적용
  AIProject/AIProject/Features/Market/MarketStore.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/SubView/CoinListHeaderView.swift
Labels: Feature

#303 대시보드 AI 브리핑 아이패드 대응
  AIProject/AIProject/Domain/Model/Dashboard/Insight.swift
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/Dashboard/View/AIBriefingView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
Labels: Design

#283 코인 상세 – 캔들 차트 버그 수정 및 리팩토링
  AIProject/AIProject/Data/API/Upbit/UpbitPriceService.swift
  AIProject/AIProject/Features/CoinDetail/Previews/ChartView+Previews.swift
  AIProject/AIProject/Features/CoinDetail/Previews/PreviewPriceService.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Refactor, Fix

#311 마켓 화면 아이폰에서 네비게이션 푸시되지 않던 버그 수정 & 디자인 적용
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Search/SearchBarView.swift
Labels: Refactor, Fix

#317 메일 문의 기능 구현
  AIProject/AIProject/Features/MyPage/View/MailView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
Labels: Feature

#318 MyPageView 아이패드 대응
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject/App/Resource/Info.plist
  AIProject/AIProject/Core/Util/String+Util.swift
  AIProject/AIProject/Domain/Model/Common/Prompt.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/CoinRowView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
Labels: Design

#323 검색 기록 저장(오래된 기록) 자동 삭제 및 기록 삭제 메서드 추가
  AIProject/AIProject/Data/DB/SearchRecord/SearchRecordManager.swift
  AIProject/AIProject/Domain/Interface/SearchRecordManaging.swift
  AIProject/AIProject/Features/Market/MarketStore.swift
Labels: Feature

#329 최근 검색 삭제 적용
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Search/RecentSearchView.swift
  AIProject/AIProject/Features/Search/SearchListView.swift
  AIProject/AIProject/Features/Search/SearchResultView.swift
  AIProject/AIProject/Features/Search/SearchView.swift
  AIProject/AIProject/Features/Search/ViewModel/SearchViewModel.swift
Labels: Feature

#330 코인 상세 뷰 아이패드 대응
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
Labels: Design

#335 앨런 새로고침 기능을 위한 공통 뷰 추가
  AIProject/AIProject/Core/Util/Date+Util.swift
  AIProject/AIProject/Features/Base/TimestampWithRefreshButtonView.swift
Labels: Design

#337 '차트' 버튼 '시세'로 변경, 공포탐욕지수 cornerRadius 수정
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
Labels: Design

#342 [재업로드] 코인 상세 - 차트 갱신 시 오른쪽 봉만 업데이트 + ProgressView 표시 개선
  AIProject/AIProject/Features/CoinDetail/View/CandleChartView.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Refactor

#338 챗봇 버그 수정
  AIProject/AIProject/Core/Remote/HTTP/ChatBotClient.swift
  AIProject/AIProject/Features/ChatBot/View/ChatScrollView.swift
  AIProject/AIProject/Features/ChatBot/ViewModel/ChatBotViewModel.swift
Labels: Refactor, Fix

#352 앱 전반에서 stroke 잘리는 부분 개선
  AIProject/AIProject/Features/Base/CircleDeleteButton.swift
  AIProject/AIProject/Features/Base/CircleIconView.swift
  AIProject/AIProject/Features/Base/DefaultProgressView.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/Base/RoundedButton.swift
  AIProject/AIProject/Features/Base/RoundedRectangleButton.swift
  AIProject/AIProject/Features/Base/RoundedRectangleFillButton.swift
  AIProject/AIProject/Features/Base/SegmentedControlView.swift
  AIProject/AIProject/Features/ChatBot/View/BotMessageView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatInputView.swift
  AIProject/AIProject/Features/ChatBot/View/UserMessageView.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportNewsSectionView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
  AIProject/AIProject/Features/Dashboard/View/RecomendationPlaceholderCardView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCardView.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/SubView/CoinListHeaderView.swift
  AIProject/AIProject/Features/Market/SubView/HeaderToggleButton.swift
  AIProject/AIProject/Features/Market/SubView/RecentCoinSectionView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkBulkInsert/ContentSection.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeRow.swift
  AIProject/AIProject/Features/Search/SearchBarView.swift
Labels: Design

#355 InsightDTO -> Insight 변환 로직을 Service로 이동
  AIProject/AIProject/Core/Util/TaskResultHandler.swift
  AIProject/AIProject/Data/API/Alan/AlanAPIService.swift
  AIProject/AIProject/Data/API/Alan/DTO/Content/InsightDTO.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/Dashboard/View/AIBriefingView.swift
  AIProject/AIProject/Features/Dashboard/View/FearGreedView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/InsightViewModel.swift
Labels: Refactor

#380 Fix/socket reconnect issue kh
  AIProject/AIProject/Features/Main/MainTabView.swift
  AIProject/AIProject/Features/Main/TabFeature.swift
  AIProject/AIProject/Features/Main/TabRouter.swift
  AIProject/AIProject/Features/Market/CoinList/CoinListView.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/SubView/CoinCell.swift
  AIProject/AIProject/Features/Market/SubView/RecentCoinSectionView.swift
  AIProject/AIProject/Features/Search/SearchBarView.swift
Labels: Feature, Fix

#372 무한스크롤 마무리...
  AIProject/AIProject/Features/Dashboard/View/CoinCarouselView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinView.swift
Labels: Feature

#383 코인 상세 - 차트 x축의 오른쪽 시간이 가려지는 현상 해결
  AIProject/AIProject/Core/Util/Calendar+Util.swift
  AIProject/AIProject/Core/Util/Date+Util.swift
  AIProject/AIProject/Features/CoinDetail/View/CandleChartView.swift
  AIProject/AIProject/Features/CoinDetail/View/ChartView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Fix

#389 투자 성향 선택 애니메이션 ThemeView와 통일
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
Labels: Design

#391 새로고침을 누르면 캐시를 사용하지 않고 네트워크 요청하도록 구현
  AIProject/AIProject/Data/API/Alan/AlanAPIService.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/InsightViewModel.swift
Labels: Feature

#388 '시세', '보고서' 탭 전환 시에도 보고서 컨텐츠 유지
  AIProject/AIProject/Domain/Model/Common/Prompt.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportNewsSectionView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
Labels: Feature

#397 마이페이지 - 테마 변경 화면 하단에 캔들차트 미리보기 추가
  AIProject/AIProject/Features/CoinDetail/ViewModel/ChartViewModel+Dummy.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemePreviewChartView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Refactor

#398 챗봇 - 채팅 입력창 배경색 수정 (.aiCoBackground → .aiCoBackgroundWhite)
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
Labels: Design

#404 헤더뷰 디자인 수정
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Design

#401 CoinDetailView 아이패드의 경우 키보드가 올라가도 차트 비율이 망가지지 않도록 수정
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
Labels: Fix

#419 온보딩에서 받아온 투자 성향 적용 등등
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject/Data/API/Alan/AlanAPIService.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
  AIProject/AIProject/Features/MyPage/View/PrivacyPolicyView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/BookmarkViewModel.swift
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
  AIProject/AIProject/Features/Onboarding/OnBoardingView.swift
  AIProject/AIProject/Features/Onboarding/OnboardingPageView.swift
Labels: Refactor, Fix

#422 뒤로가기 버튼, 제스처 활성화
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject/App/Resource/Launch Screen.storyboard
  AIProject/AIProject/Features/Base/InteractivePopGestureEnabler.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Feature

#425 ReadMe
  README.md
Labels: Design

#431 자잘한 디자인 수정
  AIProject/AIProject/Features/Base/CachedAsyncImage.swift
  AIProject/AIProject/Features/Base/CoinView.swift
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/Base/SafeAreaBackgroundView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/Dashboard/CardConst.swift
  AIProject/AIProject/Features/Dashboard/View/CoinCarouselView.swift
  AIProject/AIProject/Features/Dashboard/View/DashboardView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendCoinView.swift
  AIProject/AIProject/Features/Dashboard/View/RecommendHeaderView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/RecommendCoinViewModel.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemePreviewChartView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Design

#432 Fix/ticker decoding kh
  AIProject/AIProject.xcodeproj/project.pbxproj
  AIProject/AIProject/Data/API/Upbit/DTO/TickerDTO.swift
  AIProject/AIProject/Data/Util/DefaultDecoding.swift
  AIProject/AIProject/Data/Util/Double+Default.swift
  AIProject/AIProject/Data/Util/String+Default.swift
Labels: Feature, Fix

#435 design: 서치바 및 마켓 배경색 변경
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Search/SearchBarView.swift
Labels: Design

#438 탭바 - iOS 17에서 미지원 SF Symbols 아이콘 분기 처리
  AIProject/AIProject/Features/Main/TabFeature.swift
Labels: Fix

#437 AI 브리핑 없어도 북마크만 내보내기 활성화
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/BookmarkViewModel.swift
Labels: Feature, Refactor

#440 촐싹거리는 시세 레이블 이슈
  AIProject/AIProject/Domain/Model/Coin/TickerValue.swift
  AIProject/AIProject/Features/Market/SubView/CoinCell.swift
Labels: Feature, Refactor

#442 챗봇 아이패드 가로모드에서 입력바 길이 조정
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatInputView.swift
Labels: Refactor

#444 fix: #443 코인 리스트 셀 높이 이슈
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/SubView/CoinCell.swift
Labels: Design, Fix

#453 챗봇 -> 마이페이지 탭 화면 변경시에 레이아웃이 이상하게 뿌려지는 버그 수정
  AIProject/AIProject/Features/Main/MainTabView.swift
Labels: Fix

#454 앨런 서비스 프로토콜 파라미터 개수 변경 적용
  AIProject/AIProjectTests/RecommendCoinViewModelTests.swift
Labels: Refactor

#462 Fix/coin thumbnail export kh
  AIProject/AIProject/Domain/Interface/BookmarkManaging.swift
  AIProject/AIProject/Features/Base/CachedAsyncImage.swift
  AIProject/AIProject/Features/Base/CoinView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/CoinRowView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
  AIProject/AIProject/Features/MyPage/ViewModel/BookmarkViewModel.swift
  AIProject/AIProject/Features/MyPage/ViewModel/ImageLoader.swift
Labels: Feature

#472 대시보드 AI 브리핑 응답 글자 수가 길어지면서 UI 깨지는 현상 수정
  AIProject/AIProject/Domain/Model/Common/Prompt.swift
  AIProject/AIProject/Domain/Model/Dashboard/HeightPreferenceKey.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/Dashboard/View/AIBriefingView.swift
Labels: Fix

#477 refactor: HeaderView 멍청하게 만들기 및 분리
  AIProject/AIProject/App/Source/AIProjectApp.swift
  AIProject/AIProject/Data/API/Upbit/DefaultCoinService.swift
  AIProject/AIProject/Domain/Service/Coin/CoinStore.swift
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/Dashboard/View/CoinCarouselView.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/MyPage/View/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/CoinListSectionView.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageMenu.swift
  AIProject/AIProject/Features/MyPage/View/Main/MyPageView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
Labels: Refactor

#487 fix: 챗봇 isPortrait 로직 수정
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
Labels: Fix

#490 대시보드 스크롤이 끝까지 안되는 이슈
  AIProject/AIProject/Features/Dashboard/View/DashboardView.swift
Labels: Fix

#489 주석 달기 및 sendPing crash issue
  AIProject/AIProject/Core/Remote/WebSocket/BaseWebSocketClient.swift
  AIProject/AIProject/Core/Remote/WebSocket/ReconnectableSocket.swift
  AIProject/AIProject/Data/API/Upbit/UpbitTickerService.swift
  AIProject/AIProject/Features/Base/CachedAsyncImage.swift
  AIProject/AIProject/Features/Base/CoinView.swift
  AIProject/AIProject/Features/Main/TabRouter.swift
  AIProject/AIProject/Features/Market/CoinList/TickerViewModel.swift
  AIProject/AIProject/Features/Market/MarketStore.swift
  AIProject/AIProject/Features/Market/MarketView.swift
  AIProject/AIProject/Features/Market/SubView/BlinkBorderOnChange.swift
  AIProject/AIProject/Features/Market/SubView/BlinkUnderlineOnChange.swift
  AIProject/AIProject/Features/Market/SubView/CoinCell.swift
Labels: Docs, Fix

#491 hotfix - 현진님 TestCase CoinStore init 에러 나는 거 이슈
  AIProject/AIProjectTests/BookmarkExportTests.swift
Labels: Test, Fix

#492 코인 추천 테스트 호출 변경
  AIProject/AIProjectTests/RecommendCoinViewModelTests.swift
Labels: Refactor, Fix

#493 불필요한 로그 제거, 주석 추가
  AIProject/AIProject/Core/Remote/HTTP/ChatBotClient.swift
  AIProject/AIProject/Features/ChatBot/View/BotMessageView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatBotView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatInputView.swift
  AIProject/AIProject/Features/ChatBot/View/ChatScrollView.swift
  AIProject/AIProject/Features/ChatBot/View/UserMessageView.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/RecommendCoinViewModel.swift
  AIProject/AIProject/Features/Search/ViewModel/SearchViewModel.swift
Labels: Refactor

#494 Test/socket remove kh
  AIProject/AIProject.xcodeproj/xcshareddata/xcschemes/AIProjectTests.xcscheme
  AIProject/AIProjectTests/ReconnectableWebSocketTests.swift
  AIProject/AIProjectTests/Socket/WebSocketTests.swift
Labels: Test

#497 자잘한 디자인 수정
  AIProject/AIProject/Features/Base/HeaderView.swift
  AIProject/AIProject/Features/Dashboard/View/DashboardView.swift
  AIProject/AIProject/Features/MyPage/View/Bookmark/BookmarkView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemePreviewChartView.swift
  AIProject/AIProject/Features/MyPage/View/Theme/ThemeView.swift
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
Labels: Design
