Repository ESTiOSAI/iCo, pull requests merged in 2025-10, with the labels that each got.

#566 구글 이메일 교체
  AIProject/iCo/Features/MyPage/View/MailView.swift
Labels: Refactor

#565 대시보드 UI 수정
  AIProject/iCo/Core/Util/CGFloat+Util.swift
  AIProject/iCo/Features/Dashboard/CardConst.swift
  AIProject/iCo/Features/Dashboard/View/CoinCarouselView.swift
  AIProject/iCo/Features/Dashboard/View/DashboardView.swift
  AIProject/iCo/Features/Dashboard/View/RecomendationPlaceholderCardView.swift
  AIProject/iCo/Features/Dashboard/View/RecommendCoinView.swift
  AIProject/iCo/Features/Dashboard/View/RecommendHeaderView.swift
Labels: Design, Refactor, Docs

#569 Gemini 문제 해결 가이드에 맞춰 NetworkError 수정
  AIProject/iCo/Core/Remote/HTTP/NetworkClient.swift
  AIProject/iCo/Core/Remote/NetworkError.swift
Labels: Refactor

#570 Crashlytics google service 교체
  .gitignore
Labels: Docs

#572 이미지 파이프라인
  AIProject/iCo/Features/Base/CachedAsyncImage.swift
  AIProject/iCo/Features/MyPage/ViewModel/ImageLoader.swift
Labels: Feature, Refactor

#595 [Hotfix] 신규 상장 로직 재추가 & 대시보드/북마크에도 신규 상장 판단 연동
  AIProject/iCo/Features/CoinDetail/View/ChartView.swift
  AIProject/iCo/Features/CoinDetail/ViewModel/ChartViewModel.swift
  AIProject/iCo/Features/Dashboard/View/CoinCarouselView.swift
  AIProject/iCo/Features/Market/MarketView.swift
  AIProject/iCo/Features/MyPage/View/CoinListSectionView.swift
Labels: Fix

#600 Alan 관련 코드 삭제
  AIProject/iCo/App/Resource/Info.plist
  AIProject/iCo/Data/API/Alan/AlanAPIService.swift
  AIProject/iCo/Data/API/Alan/DTO/AlanResponseDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/CoinArticleDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/CoinOverviewDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/CoinTodayNewsDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/CoinWeeklyDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/InsightDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/PortfolioBriefingDTO.swift
  AIProject/iCo/Data/API/Gemini/DTO/RecommendCoinDTO.swift
  AIProject/iCo/Data/API/Gemini/GeminiEndpoint.swift
  AIProject/iCo/Domain/Interface/AlanAPIServiceProtocol.swift
  AIProject/iCo/Domain/Model/Common/LLMAction.swift
  AIProject/iCo/Domain/Model/Image/ImageProcessError.swift
  AIProject/iCo/Features/CoinDetail/ViewModel/ReportViewModel.swift
Labels: Refactor
