Repository ESTiOSAI/iCo, pull requests merged in 2025-09, with the labels that each got.

#498 코드 정리 (주석 추가, 불필요한 print 삭제, 줄 정렬, 파일 이동)
  AIProject/AIProject/Core/Local/UserDefaults/AppStorageKey.swift
  AIProject/AIProject/Data/API/Alan/DTO/Content/RecommendCoinDTO.swift
  AIProject/AIProject/Data/API/Reddit/DTO/RedditResponseDTO.swift
  AIProject/AIProject/Domain/Interface/AlanAPIServiceProtocol.swift
  AIProject/AIProject/Domain/Model/Coin/Coin.swift
  AIProject/AIProject/Domain/Model/Common/ResponseStatus.swift
  AIProject/AIProject/Features/Base/ReportSectionView.swift
  AIProject/AIProject/Features/CoinDetail/View/CoinDetailView.swift
  AIProject/AIProject/Features/CoinDetail/View/ReportView.swift
  AIProject/AIProject/Features/CoinDetail/ViewModel/ReportViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/FearGreedViewModel.swift
  AIProject/AIProject/Features/Dashboard/ViewModel/InsightViewModel.swift
  AIProject/AIProject/Features/MyPage/View/Bookmark/ShareablePNGReport.swift
  AIProject/AIProject/Features/MyPage/View/MailView.swift
  AIProject/AIProject/Features/MyPage/View/NoEmailGuideView.swift
  AIProject/AIProject/Features/Onboarding/LastOnboardingPage.swift
Labels: Refactor

#499 주석 수정
  AIProject/AIProject/Data/API/Alan/AlanAPIService.swift
Labels: Docs

#532 Alan -> Gemini
  AIProject/iCo/App/Resource/Info.plist
  AIProject/iCo/Core/Util/Date+Util.swift
  AIProject/iCo/Data/API/Alan/AlanAPIService.swift
  AIProject/iCo/Data/API/Alan/DTO/Content/CoinWeeklyDTO.swift
  AIProject/iCo/Data/API/Gemini/GeminiEndpoint.swift
  AIProject/iCo/Data/API/Gemini/LLMAPIService.swift
  AIProject/iCo/Domain/Model/Common/Prompt.swift
  AIProject/iCo/Features/CoinDetail/ViewModel/ReportViewModel.swift
  AIProject/iCo/Features/Dashboard/View/FearGreedView.swift
  AIProject/iCo/Features/Dashboard/ViewModel/InsightViewModel.swift
Labels: Feature, Refactor

#535 코인 시세 API 디코드 이슈
  AIProject/iCo/Core/Remote/WebSocket/BaseWebSocketClient.swift
  AIProject/iCo/Data/API/Upbit/DTO/TickerDTO.swift
  AIProject/iCo/Data/API/Upbit/UpbitAPIService.swift
  AIProject/iCo/Data/Util/Int + Default.swift
  AIProject/iCo/Features/Base/HeaderView.swift
  AIProject/iCoTests/UpbitTicketEncodeTests.swift
Labels: Fix

#540 캔들 차트 - 보이는 구간 기준 Y축 자동 스케일링 적용
  AIProject/iCo/Features/CoinDetail/View/CandleChartView.swift
Labels: Feature

#541 캔들 차트 - 코인 상세 진입 시 헤더 티커를 단일 마켓으로 조회하도록 수정
  AIProject/iCo/Features/CoinDetail/ViewModel/ChartViewModel.swift
Labels: Fix
